#yum install golang -y
#cp dispatch.service /etc/systemd/system/dispatch.service
#useradd roboshop
#mkdir /app
#curl -L -o /tmp/dispatch.zip https://roboshop-artifacts.s3.amazonaws.com/dispatch.zip
#cd /app
#unzip /tmp/dispatch.zip
#cd /app
#go mod init dispatch
#go get
#go build
#systemctl daemon-reload
#systemctl enable dispatch
#systemctl restart dispatch

- name: Install & config Dispatch
  hosts: all
  become: true
  vars:
    component: dispatch
  tasks:
    - name: install golang
      ansible.builtin.yum:
        name: golang
        state: installed

    - name: calling app-preq
      ansible.builtin.import_tasks: app-preq.yml

    - name: go commands
      ansible.built.shell: go mod init dispatch ; go get ; go build

    - name: calling systemsd
      ansible.builtin.import_tasks: systemd-setup.yml



