#yum install python36 gcc python3-devel -y
#cp payment.service /etc/systemd/system/payment.service
#useradd roboshop
#rm -rf /app
#mkdir /app
#curl -L -o /tmp/payment.zip https://roboshop-artifacts.s3.amazonaws.com/payment.zip
#cd /app
#unzip /tmp/payment.zip
#cd /app
#pip3.6 install -r requirements.txt
#systemctl daemon-reload
#systemctl enable payment
#systemctl restart payment

- name: Payment Install & config
  hosts: all
  become: true
  vars:
    component: payment
  tasks:
    - name: Install python
      ansible.builtin.yum:
        name:
          - python36
          - gcc
          - python3-devel
        state: installed

    - name: calling app-preq
      ansible.builtin.import_tasks: app-preq.yml

    - name: install pip requirements
      ansible.builtin.shell: pip3.6 install -r requirements.txt
      args:
        chdir: /app

    - name: calling systemd
      ansible.builtin.import_tasks: systemd-setup.yml