- name: Redis Configuration setup
  hosts: all
  become: true
  tasks:
    - name: Install redis repo
      ansible.builtin.shell: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

    - name: enable redis Module
      ansible.builtin.shell: yum module enable redis:remi-6.2 -y

    - name: install redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: Replace redis listen add /etc/redis.conf
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Replace redis listen add /etc/redis/redis.conf
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start redis
      ansible.builtin.systemd:
        name: redis
        state: restarted
        daemon_reload: yes




